apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: ${NAMESPACE}
  labels:
    app: etcd
spec:
  serviceName: etcd
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      name: etcd
      labels:
        app: etcd
    spec:
      volumes:
        - name: config
          configMap:
            name: etcd-config
            defaultMode: 0777
        - name: server-certs
          secret:
            secretName: etcd-server-certs
        - name: client-certs
          secret:
            secretName: etcd-client-certs
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.3.25
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          volumeMounts:
            - mountPath: /scripts
              name: config
              readOnly: true
            - name: server-certs
              mountPath: /etc/etcd/certs/
              readOnly: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /bin/sh
            - -c
            - |
              cp /scripts/etcd.sh /tmp
              chmod +x /tmp/etcd.sh
              /tmp/etcd.sh
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: ${NAMESPACE}
  labels:
    app: etcd
spec:
  clusterIP: None
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  selector:
    app: etcd